### ISSUE TITLE
Service Logic

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/Tim-Quayle#2]
https://github.com/CodingDojo-MEAN-06-18/Tim-Quayle/blob/721fc737cd7aa00ce883264e1d90da5b51e76528/ninja-gold/src/app/building/building.component.ts#L21-L30

Consider letting your service handle the majority of this logic. You could pass it the location and min/max gold and allow it to stream updated gold information to subscriber components. After that does the component need local gold information? If it (the service) also generated new messages based on that information you might not need to `emit` your gold object. Stream new messages with another `BehaviorSubject`.

**Comment by timquayle** [comment]
Jason, some of what your are seeing is, I first did the project using
nothing but input/output methods, after I finished the service chapter I
went back and used observables In it, and some of that code is just
residual from my first version.. I think this assignment would make alot
more sense if it was placed after we learn about observables, which as it
is now, it's before. But thanks for the feedback, I will go ahead and
offlload most of my logic into service.

Thanks,
Tim

**Comment by dojo-json** [comment]
Thanks for the clarification. And I totally agree, the overview of `Observables` should certainly come before this and the Number Service assignment.

**Comment by timquayle** [comment]
Done, and done.. thanks!
